ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "billingType" TEXT NOT NULL DEFAULT 'once';
ALTER TABLE "Proposal" ADD COLUMN IF NOT EXISTS "commercial" JSONB;
ALTER TABLE "ProposalItem" ADD COLUMN IF NOT EXISTS "billingType" TEXT NOT NULL DEFAULT 'once', ADD COLUMN IF NOT EXISTS "optional" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN IF NOT EXISTS "selected" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN IF NOT EXISTS "packageId" TEXT NOT NULL DEFAULT '', ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0;
