'use client';
import { usePlatformStore } from '@/store/usePlatformStore';
import { COMMERCIAL_MODELS, newCommercialConfig, commercialTotals, type CommercialConfig } from '@/lib/commercial';
import { formatBRL, toCents, toReais } from '@/lib/money';

const input = 'mt-2 w-full rounded-xl border border-[var(--border-color)] bg-[var(--background)] p-3 text-sm text-[var(--foreground)] focus:outline-[#FF6A00]';
export function CommercialEditor() {
  const { quoteDraft: draft, updateQuoteDraft: update } = usePlatformStore();
  const c = draft.commercial ?? newCommercialConfig();
  const patch = (data: Partial<CommercialConfig>) => update({ commercial: { ...c, ...data } });
  const items = draft.services.map(s => ({ ...s, unitPrice: s.price }));
  const totals = commercialTotals(items, c);
  return <section className="mb-8 space-y-6 text-[var(--foreground)]">
    <div><p className="mb-2 text-xs font-bold uppercase tracking-widest text-[#FF6A00]">Modelo comercial</p><h2 className="text-2xl font-bold">Como você vai apresentar esta oferta?</h2><p className="mt-2 text-sm text-[var(--text-muted)]">A aparência é escolhida na próxima tela. Aqui você define escopo, valores e cobrança.</p></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{COMMERCIAL_MODELS.map(m => <button key={m.id} type="button" aria-pressed={c.model === m.id} onClick={() => update({ commercial: { ...c, model: m.id }, template: m.template, services: draft.services.map(s => ({ ...s, billingType: m.id === 'monthly' ? 'monthly' : ['fixed', 'items'].includes(m.id) ? 'once' : s.billingType ?? 'once', packageId: m.id === 'packages' ? s.packageId ?? '' : '' })) })} className={`rounded-2xl border p-5 text-left transition-colors ${c.model === m.id ? 'border-[#FF6A00] bg-[#FF6A00]/10' : 'border-[var(--border-color)] bg-[var(--panel-bg)] hover:border-[#FF6A00]/50'}`}><strong className="block text-sm">{m.name}</strong><span className="mt-2 block text-xs leading-relaxed text-[var(--text-muted)]">{m.description}</span></button>)}</div>
    <div className="rounded-3xl border border-[var(--border-color)] bg-[var(--panel-bg)] p-5 sm:p-7">
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-sm">Primeiro vencimento<input aria-label="Primeiro vencimento" type="date" className={input} value={c.firstDueDate} onChange={e => patch({ firstDueDate: e.target.value })}/></label>
        <label className="text-sm">Parcelas do valor único<input aria-label="Parcelas do valor único" type="number" min="1" max="48" className={input} value={c.installments} onChange={e => patch({ installments: Number(e.target.value) })}/></label>
        {['monthly', 'hybrid', 'packages'].includes(c.model) && <><label className="text-sm">Vigência (meses)<input aria-label="Vigência em meses" type="number" min="1" max="60" className={input} value={c.months} onChange={e => patch({ months: Number(e.target.value) })}/></label><label className="text-sm">Permanência mínima (meses)<input aria-label="Permanência mínima em meses" type="number" min="0" max={c.months} className={input} value={c.commitmentMonths} onChange={e => patch({ commitmentMonths: Number(e.target.value) })}/></label></>}
      </div>
      <p className="mt-3 text-xs text-[var(--text-muted)]">O aceite gera as cobranças no portal. Parcelamento divide o valor único; mensalidade se repete durante a vigência.</p>
      {c.model === 'packages' && <div className="mt-6 grid gap-3 sm:grid-cols-3">{c.packages.map(p => <label key={p.id} className="text-xs">Nome do pacote<input aria-label={`Nome do pacote ${p.id}`} className={input} value={p.name} onChange={e => patch({ packages: c.packages.map(v => v.id === p.id ? { ...v, name: e.target.value } : v) })}/></label>)}</div>}
      <div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm">O que não está incluído<textarea className={input} rows={3} value={c.exclusions} placeholder="Ex.: hospedagem, mídia paga e produção de fotos." onChange={e => patch({ exclusions: e.target.value })}/></label><label className="text-sm">Revisões e alterações de escopo<textarea className={input} rows={3} value={c.revisions} placeholder="Ex.: duas rodadas de revisão. Novas entregas serão orçadas à parte." onChange={e => patch({ revisions: e.target.value })}/></label></div>
    </div>
    {draft.services.length > 0 && <div className="space-y-4"><h3 className="text-lg font-bold">Composição da oferta</h3>{draft.services.map(s => {
      const edit = (data: Partial<typeof s>) => update({ services: draft.services.map(v => v.id === s.id ? { ...v, ...data } : v) });
      return <div key={s.id} className="rounded-2xl border border-[var(--border-color)] bg-[var(--panel-bg)] p-5"><div className="flex items-start justify-between gap-4"><strong>{s.name}</strong><button type="button" aria-label={`Remover ${s.name} da proposta`} onClick={() => update({ services: draft.services.filter(v => v.id !== s.id) })} className="text-xs text-[var(--text-muted)] underline">Remover</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-xs">Quantidade<input aria-label={`Quantidade de ${s.name}`} type="number" min="0.01" step="any" className={input} value={s.quantity} onChange={e => edit({ quantity: Number(e.target.value) })}/></label>
        <label className="text-xs">Valor unitário (R$)<input aria-label={`Valor de ${s.name}`} type="number" min="0" step="0.01" className={input} value={toReais(s.price)} onChange={e => edit({ price: toCents(e.target.value) })}/></label>
        <label className="text-xs">Cobrança<select aria-label={`Cobrança de ${s.name}`} className={input} value={s.billingType ?? 'once'} onChange={e => edit({ billingType: e.target.value as 'once' | 'monthly' })}><option value="once">Valor único</option><option value="monthly">Mensalidade</option></select></label>
        {c.model === 'packages' && <label className="text-xs">Pacote<select aria-label={`Pacote de ${s.name}`} className={input} value={s.packageId ?? ''} onChange={e => edit({ packageId: e.target.value })}><option value="">Todos os pacotes</option>{c.packages.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
      </div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs">Descrição<textarea className={input} value={s.description} onChange={e => edit({ description: e.target.value })}/></label><label className="text-xs">Entregáveis (um por linha)<textarea className={input} rows={3} value={s.details.join('\n')} onChange={e => edit({ details: e.target.value.split('\n') })}/></label></div><div className="mt-3 flex gap-4"><button type="button" className="text-xs underline" onClick={() => update({ services: [...draft.services, { ...s, id: crypto.randomUUID(), name: s.name + ' — cópia' }] })}>Duplicar item</button></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={s.optional ?? false} onChange={e => edit({ optional: e.target.checked, selected: false })} className="accent-[#FF6A00]"/>Adicional opcional — o cliente escolhe antes do aceite</label></div>;
    })}<div className="flex flex-wrap justify-between gap-4 rounded-2xl bg-[#FF6A00]/10 p-5 text-sm" aria-live="polite"><span>Valor único <strong>{formatBRL(totals.once)}</strong></span><span>Mensalidade <strong>{formatBRL(totals.monthly)}</strong></span><span>Total da seleção <strong>{formatBRL(totals.total)}</strong></span></div></div>}
  </section>;
}
